GENOME_FA: resources/dmel-all-chromosome-r6.41.fasta.gz
GTF: resources/dmel-all-r6.41.gtf.gz
TFS: resources/Drosophila_melanogaster_TF.txt
COFACS: resources/Drosophila_melanogaster_TF_cofactors.txt
TE_FA: resources/Tidalbase_transposon_sequence.fasta
S2_CHROMSTATE: resources/chromstate_s2_9state_r5todm6.bed.gz
MERGED_MODELS: upstream/final-models.collected-info.tsv.gz
THIS_STUDY_RNAI: upstream/kd.se.gene.0.rds
THIS_STUDY_DGRP_RNA: upstream/se.gene.0.rds
DGRP_TIDAL: upstream/DGRP_flies.tsv.gz
TE_CLASSES: resources/Tidalbase_Dmel_TE_classifications_2015.txt
REPEATMASKER_BED: resources/plus-repeats.repeatmasked.fixednames.bed

S2RPLUS_RNAI_SE: upstream/tfrnai.se.gene.0.rds
S2RPLUS_RNAI_RUNSELECTOR: resources/full_tfrnai_srarunselector.txt
S2RPLUS_RNAI_BATCH: resources/batch_data.tsv.gz

BBMASK_ENTROPY: 0.7
BBMASK_W: 12

MASH_ARGS: '-k 11 -s 1000'
EXPECTED_MASH_DIST_NPERM: 1000

BOOTRANGES_REPS: 1000
BOOTRANGES_SEGLENGTH: 1e5
BOOTRANGES_BLOCKLENGTH: 5e5
BOOTRANGES_NSEG: 3

REWIRING_ANALYSIS:
  TSS_DIST: 5000
  MAX_TES_PER_GENE: 100 # effectively inf
  COEF_QUANTILE_CUTOFF: 0.5 # effectively inf
  MIN_PCT_FIXATION: 0.25
  MAX_PCT_FIXATION: 0.75

LM_CARTOON: resources/simple_linmod_methods_v01.png